spring:
  datasource:
    url: jdbc:h2:mem:video-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

aws:
  region: us-east-1
  s3:
    bucket-name: videos-hackathon
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/395368505712/video-processing-queue

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
